/**
 * Cross-cutting, stable error codes shared by the API and all clients.
 * Module-specific codes are added in later phases alongside their modules.
 */
export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // --- Phase 03: auth/RBAC/settings/audit ---
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  CANNOT_DELETE_SELF: "CANNOT_DELETE_SELF",
  CANNOT_DELETE_SUPER_ADMIN: "CANNOT_DELETE_SUPER_ADMIN",
  CANNOT_REMOVE_CRITICAL_PERMISSION: "CANNOT_REMOVE_CRITICAL_PERMISSION",
  CANNOT_MODIFY_SYSTEM_ROLE: "CANNOT_MODIFY_SYSTEM_ROLE",
  ROLE_IN_USE: "ROLE_IN_USE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
